use super::{Binding, Ctx, Key};
use crate::tui::app::event::Action;

const fn b(
    ctx: Ctx,
    seq: &'static [Key],
    action: Action,
    label: &'static str,
    desc: &'static str,
) -> Binding {
    Binding {
        ctx,
        seq,
        action,
        label,
        desc,
    }
}

/// The single built-in keymap. Users customize individual keys via the
/// `keybinding` config section (see [`build_table`]). The help overlay renders
/// directly from these rows so it always matches the active bindings + context.
static BINDINGS: &[Binding] = &[
    // Global
    b(Ctx::Global, &[Key::ch('q')], Action::Quit, "q", "quit"),
    b(
        Ctx::Global,
        &[Key::ch('?')],
        Action::Help,
        "?",
        "toggle help",
    ),
    b(
        Ctx::Global,
        &[Key::ch('`')],
        Action::Jobs,
        "`",
        "job tracker",
    ),
    b(
        Ctx::Global,
        &[Key::ch('S')],
        Action::Settings,
        "S",
        "settings",
    ),
    b(
        Ctx::Global,
        &[Key::ch('L')],
        Action::FocusNext,
        "L",
        "focus pane right",
    ),
    b(
        Ctx::Global,
        &[Key::ch('H')],
        Action::FocusPrev,
        "H",
        "focus pane left",
    ),
    b(
        Ctx::Global,
        &[Key::ch('z')],
        Action::ToggleSidebar,
        "z",
        "collapse sidebar",
    ),
    b(
        Ctx::Global,
        &[Key::ch('R')],
        Action::Refresh,
        "R",
        "refresh mailbox",
    ),
    // Sidebar
    b(Ctx::Sidebar, &[Key::ch('j')], Action::MoveDown, "j", "down"),
    b(Ctx::Sidebar, &[Key::ch('k')], Action::MoveUp, "k", "up"),
    b(Ctx::Sidebar, &[Key::ch('G')], Action::MoveLast, "G", "last"),
    b(
        Ctx::Sidebar,
        &[Key::ch('g'), Key::ch('g')],
        Action::MoveFirst,
        "gg",
        "first",
    ),
    b(
        Ctx::Sidebar,
        &[Key::ch('o')],
        Action::SelectFolder,
        "o",
        "open mailbox / switch account",
    ),
    b(
        Ctx::Sidebar,
        &[Key::ch('l')],
        Action::ExpandFolder,
        "l",
        "expand / switch account",
    ),
    b(
        Ctx::Sidebar,
        &[Key::ch('h')],
        Action::CollapseFolder,
        "h",
        "collapse folder",
    ),
    b(
        Ctx::Sidebar,
        &[Key::right()],
        Action::ExpandFolder,
        "→",
        "expand",
    ),
    b(
        Ctx::Sidebar,
        &[Key::left()],
        Action::CollapseFolder,
        "←",
        "collapse",
    ),
    b(
        Ctx::Sidebar,
        &[Key::ch('/')],
        Action::FilterAccounts,
        "/",
        "filter accounts",
    ),
    // List
    b(Ctx::List, &[Key::ch('j')], Action::MoveDown, "j", "down"),
    b(Ctx::List, &[Key::ch('k')], Action::MoveUp, "k", "up"),
    b(Ctx::List, &[Key::ch('G')], Action::MoveLast, "G", "last"),
    b(Ctx::List, &[Key::page_up()], Action::PageUp, "PgUp", "page up"),
    b(Ctx::List, &[Key::page_down()], Action::PageDown, "PgDn", "page down"),
    b(
        Ctx::List,
        &[Key::ch('g'), Key::ch('g')],
        Action::MoveFirst,
        "gg",
        "first",
    ),
    b(
        Ctx::List,
        &[Key::enter()],
        Action::OpenMessage,
        "Enter",
        "open message",
    ),
    b(
        Ctx::List,
        &[Key::ch('o')],
        Action::OpenMessage,
        "o",
        "open message",
    ),
    b(
        Ctx::List,
        &[Key::ch(' ')],
        Action::ToggleMark,
        "Space",
        "mark / unmark",
    ),
    b(
        Ctx::List,
        &[Key::ch('u')],
        Action::ToggleUnread,
        "u",
        "toggle unread",
    ),
    b(
        Ctx::List,
        &[Key::ch('s')],
        Action::ToggleFlag,
        "s",
        "flag / star",
    ),
    b(
        Ctx::List,
        &[Key::ch('d')],
        Action::Delete,
        "d",
        "delete (confirm)",
    ),
    b(Ctx::List, &[Key::ch('a')], Action::Archive, "a", "archive"),
    b(Ctx::List, &[Key::ch('/')], Action::Search, "/", "search"),
    b(
        Ctx::List,
        &[Key::ch('n')],
        Action::SearchNext,
        "n",
        "next match",
    ),
    b(
        Ctx::List,
        &[Key::ch('N')],
        Action::SearchPrev,
        "N",
        "prev match",
    ),
    b(
        Ctx::List,
        &[Key::ch('O')],
        Action::OpenInBrowser,
        "O",
        "open in browser",
    ),
    b(Ctx::List, &[Key::ch('c')], Action::Compose, "c", "compose"),
    b(Ctx::List, &[Key::ch('r')], Action::Reply, "r", "reply"),
    b(Ctx::List, &[Key::ch('f')], Action::Forward, "f", "forward"),
    b(
        Ctx::List,
        &[Key::esc()],
        Action::Back,
        "Esc",
        "back to folders",
    ),
    // Reader
    b(
        Ctx::Reader,
        &[Key::ch('j')],
        Action::ScrollDown,
        "j",
        "scroll down",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('k')],
        Action::ScrollUp,
        "k",
        "scroll up",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('G')],
        Action::ScrollEnd,
        "G",
        "bottom",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('g'), Key::ch('g')],
        Action::ScrollStart,
        "gg",
        "top",
    ),
    b(Ctx::Reader, &[Key::cc('u')], Action::ScrollHalfUp, "C-u", "half page up"),
    b(Ctx::Reader, &[Key::cc('d')], Action::ScrollHalfDown, "C-d", "half page down"),
    b(Ctx::Reader, &[Key::ch('r')], Action::Reply, "r", "reply"),
    b(
        Ctx::Reader,
        &[Key::ch('f')],
        Action::Forward,
        "f",
        "forward",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('o')],
        Action::OpenAttachment,
        "o",
        "open attachment",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('O')],
        Action::OpenInBrowser,
        "O",
        "open in browser",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('h')],
        Action::ToggleHeaders,
        "h",
        "toggle full headers",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('d')],
        Action::Delete,
        "d",
        "delete (confirm)",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('a')],
        Action::Archive,
        "a",
        "archive",
    ),
    b(
        Ctx::Reader,
        &[Key::esc()],
        Action::Back,
        "Esc",
        "back to list",
    ),
    // Compose (inline header fields; the body is edited in $EDITOR). Actual
    // dispatch is in `App::compose_key`; these rows drive the help overlay.
    b(
        Ctx::Compose,
        &[Key::tab()],
        Action::FocusNext,
        "Tab/jk",
        "move field",
    ),
    b(
        Ctx::Compose,
        &[Key::cc('e')],
        Action::ExternalEditor,
        "Ctrl-e",
        "edit body in $EDITOR",
    ),
    b(
        Ctx::Compose,
        &[Key::cc('s')],
        Action::Send,
        "Ctrl-s",
        "send",
    ),
    b(
        Ctx::Compose,
        &[Key::cc('d')],
        Action::SaveDraft,
        "Ctrl-d",
        "save draft",
    ),
    b(
        Ctx::Compose,
        &[Key::esc()],
        Action::DiscardDraft,
        "Esc",
        "discard",
    ),
    // Settings
    b(
        Ctx::Settings,
        &[Key::tab()],
        Action::FocusNext,
        "Tab",
        "next field",
    ),
    b(
        Ctx::Settings,
        &[Key::ch('W')],
        Action::SaveSettings,
        "W",
        "save changes",
    ),
    b(
        Ctx::Settings,
        &[Key::esc()],
        Action::CloseSettings,
        "Esc",
        "back",
    ),
    // Search
    b(
        Ctx::Search,
        &[Key::enter()],
        Action::CommitSearch,
        "Enter",
        "apply search",
    ),
    b(
        Ctx::Search,
        &[Key::esc()],
        Action::CloseOverlay,
        "Esc",
        "close",
    ),
    // Confirm
    b(
        Ctx::Confirm,
        &[Key::ch('y')],
        Action::ConfirmYes,
        "y",
        "confirm",
    ),
    b(
        Ctx::Confirm,
        &[Key::enter()],
        Action::ConfirmYes,
        "Enter",
        "confirm",
    ),
    b(
        Ctx::Confirm,
        &[Key::ch('n')],
        Action::ConfirmNo,
        "n",
        "cancel",
    ),
    b(
        Ctx::Confirm,
        &[Key::esc()],
        Action::ConfirmNo,
        "Esc",
        "cancel",
    ),
];

/// All built-in bindings, for the help overlay and table building.
pub fn bindings() -> &'static [Binding] {
    BINDINGS
}
