use super::{Binding, Ctx, Key};
use crate::ui::app::event::Action;

const fn b(
    ctx: Ctx,
    seq: &'static [Key],
    action: Action,
    label: &'static str,
    desc: &'static str,
) -> Binding {
    Binding {
        ctx,
        seq,
        action,
        label,
        desc,
    }
}

/// The single built-in keymap. Users customize individual keys via the
/// `keybinding` config section (see [`build_table`]). The help overlay renders
/// directly from these rows so it always matches the active bindings + context.
static BINDINGS: &[Binding] = &[
    // Global
    b(Ctx::Global, &[Key::ch('q')], Action::Quit, "q", "quit"),
    b(
        Ctx::Global,
        &[Key::ch('?')],
        Action::Help,
        "?",
        "toggle help",
    ),
    b(
        Ctx::Global,
        &[Key::ch('`')],
        Action::Jobs,
        "`",
        "job tracker",
    ),
    b(
        Ctx::Global,
        &[Key::ch('S')],
        Action::Settings,
        "S",
        "settings",
    ),
    b(
        Ctx::Global,
        &[Key::ch('L')],
        Action::FocusNext,
        "L",
        "focus pane right",
    ),
    b(
        Ctx::Global,
        &[Key::ch('H')],
        Action::FocusPrev,
        "H",
        "focus pane left",
    ),
    b(
        Ctx::Global,
        &[Key::ch('z')],
        Action::ToggleSidebar,
        "z",
        "collapse sidebar",
    ),
    b(
        Ctx::Global,
        &[Key::ch('R')],
        Action::Refresh,
        "R",
        "refresh mailbox",
    ),
    // Sidebar
    b(Ctx::Sidebar, &[Key::ch('j')], Action::MoveDown, "j", "down"),
    b(Ctx::Sidebar, &[Key::ch('k')], Action::MoveUp, "k", "up"),
    b(Ctx::Sidebar, &[Key::ch('G')], Action::MoveLast, "G", "last"),
    b(
        Ctx::Sidebar,
        &[Key::ch('g'), Key::ch('g')],
        Action::MoveFirst,
        "gg",
        "first",
    ),
    b(
        Ctx::Sidebar,
        &[Key::ch('o')],
        Action::SelectFolder,
        "o",
        "open mailbox / switch account",
    ),
    b(
        Ctx::Sidebar,
        &[Key::ch('l')],
        Action::ExpandFolder,
        "l",
        "expand / switch account",
    ),
    b(
        Ctx::Sidebar,
        &[Key::ch('h')],
        Action::CollapseFolder,
        "h",
        "collapse folder",
    ),
    b(
        Ctx::Sidebar,
        &[Key::right()],
        Action::ExpandFolder,
        "→",
        "expand",
    ),
    b(
        Ctx::Sidebar,
        &[Key::left()],
        Action::CollapseFolder,
        "←",
        "collapse",
    ),
    b(
        Ctx::Sidebar,
        &[Key::ch('/')],
        Action::FilterAccounts,
        "/",
        "filter accounts",
    ),
    // List
    b(Ctx::List, &[Key::ch('j')], Action::MoveDown, "j", "down"),
    b(Ctx::List, &[Key::ch('k')], Action::MoveUp, "k", "up"),
    b(Ctx::List, &[Key::ch('G')], Action::MoveLast, "G", "last"),
    b(Ctx::List, &[Key::page_up()], Action::PageUp, "PgUp", "page up"),
    b(Ctx::List, &[Key::page_down()], Action::PageDown, "PgDn", "page down"),
    b(
        Ctx::List,
        &[Key::ch('g'), Key::ch('g')],
        Action::MoveFirst,
        "gg",
        "first",
    ),
    b(
        Ctx::List,
        &[Key::enter()],
        Action::OpenMessage,
        "Enter",
        "open message",
    ),
    b(
        Ctx::List,
        &[Key::ch('o')],
        Action::OpenMessage,
        "o",
        "open message",
    ),
    b(
        Ctx::List,
        &[Key::ch(' ')],
        Action::ToggleMark,
        "Space",
        "mark / unmark",
    ),
    b(
        Ctx::List,
        &[Key::ch('u')],
        Action::ToggleUnread,
        "u",
        "toggle unread",
    ),
    b(
        Ctx::List,
        &[Key::ch('s')],
        Action::ToggleFlag,
        "s",
        "flag / star",
    ),
    b(
        Ctx::List,
        &[Key::ch('d')],
        Action::Delete,
        "d",
        "delete (confirm)",
    ),
    b(Ctx::List, &[Key::ch('a')], Action::Archive, "a", "archive"),
    b(Ctx::List, &[Key::ch('/')], Action::Search, "/", "search"),
    b(
        Ctx::List,
        &[Key::ch('n')],
        Action::SearchNext,
        "n",
        "next match",
    ),
    b(
        Ctx::List,
        &[Key::ch('N')],
        Action::SearchPrev,
        "N",
        "prev match",
    ),
    b(
        Ctx::List,
        &[Key::ch('O')],
        Action::OpenInBrowser,
        "O",
        "open in browser",
    ),
    b(Ctx::List, &[Key::ch('c')], Action::Compose, "c", "compose"),
    b(Ctx::List, &[Key::ch('r')], Action::Reply, "r", "reply"),
    b(Ctx::List, &[Key::ch('f')], Action::Forward, "f", "forward"),
    b(
        Ctx::List,
        &[Key::esc()],
        Action::Back,
        "Esc",
        "back to folders",
    ),
    // Reader
    b(
        Ctx::Reader,
        &[Key::ch('j')],
        Action::ScrollDown,
        "j",
        "scroll down",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('k')],
        Action::ScrollUp,
        "k",
        "scroll up",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('G')],
        Action::ScrollEnd,
        "G",
        "bottom",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('g'), Key::ch('g')],
        Action::ScrollStart,
        "gg",
        "top",
    ),
    b(Ctx::Reader, &[Key::cc('u')], Action::ScrollHalfUp, "C-u", "half page up"),
    b(Ctx::Reader, &[Key::cc('d')], Action::ScrollHalfDown, "C-d", "half page down"),
    b(Ctx::Reader, &[Key::ch('r')], Action::Reply, "r", "reply"),
    b(
        Ctx::Reader,
        &[Key::ch('f')],
        Action::Forward,
        "f",
        "forward",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('o')],
        Action::OpenAttachment,
        "o",
        "open attachment",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('O')],
        Action::OpenInBrowser,
        "O",
        "open in browser",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('h')],
        Action::ToggleHeaders,
        "h",
        "toggle full headers",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('d')],
        Action::Delete,
        "d",
        "delete (confirm)",
    ),
    b(
        Ctx::Reader,
        &[Key::ch('a')],
        Action::Archive,
        "a",
        "archive",
    ),
    b(
        Ctx::Reader,
        &[Key::esc()],
        Action::Back,
        "Esc",
        "back to list",
    ),
    // Compose (inline header fields; the body is edited in $EDITOR). Dispatch is
    // in `App::compose_key`/`compose_nav_key`, which resolve against these rows.
    b(Ctx::Compose, &[Key::ch('j')], Action::FocusDown, "j", "next field"),
    b(Ctx::Compose, &[Key::ch('k')], Action::FocusUp, "k", "prev field"),
    b(Ctx::Compose, &[Key::ch('l')], Action::FocusRight, "l", "field right"),
    b(Ctx::Compose, &[Key::ch('h')], Action::FocusLeft, "h", "field left"),
    b(Ctx::Compose, &[Key::down()], Action::FocusDown, "↓", "next field"),
    b(Ctx::Compose, &[Key::up()], Action::FocusUp, "↑", "prev field"),
    b(Ctx::Compose, &[Key::right()], Action::FocusRight, "→", "field right"),
    b(Ctx::Compose, &[Key::left()], Action::FocusLeft, "←", "field left"),
    b(Ctx::Compose, &[Key::tab()], Action::FocusNext, "Tab", "next field"),
    b(Ctx::Compose, &[Key::back_tab()], Action::FocusPrev, "S-Tab", "prev field"),
    b(Ctx::Compose, &[Key::ch('i')], Action::EditField, "i", "edit field / body"),
    b(Ctx::Compose, &[Key::enter()], Action::EditField, "Enter", "edit field / body"),
    // Body scrolling (only when the body row is focused).
    b(Ctx::Compose, &[Key::ch('J')], Action::ScrollDown, "J", "scroll body down"),
    b(Ctx::Compose, &[Key::ch('K')], Action::ScrollUp, "K", "scroll body up"),
    b(Ctx::Compose, &[Key::ch('g'), Key::ch('g')], Action::ScrollStart, "gg", "body top"),
    b(Ctx::Compose, &[Key::home()], Action::ScrollStart, "Home", "body top"),
    b(Ctx::Compose, &[Key::ch('G')], Action::ScrollEnd, "G", "body bottom"),
    b(Ctx::Compose, &[Key::end()], Action::ScrollEnd, "End", "body bottom"),
    b(Ctx::Compose, &[Key::page_up()], Action::PageUp, "PgUp", "body page up"),
    b(Ctx::Compose, &[Key::page_down()], Action::PageDown, "PgDn", "body page down"),
    b(Ctx::Compose, &[Key::cc('e')], Action::ExternalEditor, "Ctrl-e", "edit body in $EDITOR"),
    b(Ctx::Compose, &[Key::cc('s')], Action::Send, "Ctrl-s", "send"),
    b(Ctx::Compose, &[Key::cc('d')], Action::SaveDraft, "Ctrl-d", "save draft"),
    b(Ctx::Compose, &[Key::esc()], Action::DiscardDraft, "Esc", "discard"),
    // Settings: account manager list (focus == Accounts).
    b(Ctx::Settings, &[Key::ch('j')], Action::MoveDown, "j", "down"),
    b(Ctx::Settings, &[Key::ch('k')], Action::MoveUp, "k", "up"),
    b(Ctx::Settings, &[Key::down()], Action::MoveDown, "↓", "down"),
    b(Ctx::Settings, &[Key::up()], Action::MoveUp, "↑", "up"),
    b(Ctx::Settings, &[Key::ch('o')], Action::OpenAccount, "o", "open / edit account"),
    b(Ctx::Settings, &[Key::ch('a')], Action::AddAccount, "a", "add account"),
    b(Ctx::Settings, &[Key::ch('d')], Action::DeleteAccount, "d", "delete account"),
    b(Ctx::Settings, &[Key::ch('x')], Action::SetDefaultAccount, "x", "set as default"),
    b(Ctx::Settings, &[Key::ch('/')], Action::FilterAccounts, "/", "filter accounts"),
    b(Ctx::Settings, &[Key::ch('W')], Action::SaveSettings, "W", "save changes"),
    b(Ctx::Settings, &[Key::esc()], Action::CloseSettings, "Esc", "back"),
    // Settings: account edit form (field navigation). Dispatch is in
    // `settings_edit_key`, which resolves against these rows.
    b(Ctx::SettingsForm, &[Key::ch('j')], Action::FocusDown, "j", "next field"),
    b(Ctx::SettingsForm, &[Key::ch('k')], Action::FocusUp, "k", "prev field"),
    b(Ctx::SettingsForm, &[Key::ch('l')], Action::FocusRight, "l", "field right"),
    b(Ctx::SettingsForm, &[Key::ch('h')], Action::FocusLeft, "h", "field left"),
    b(Ctx::SettingsForm, &[Key::down()], Action::FocusDown, "↓", "next field"),
    b(Ctx::SettingsForm, &[Key::up()], Action::FocusUp, "↑", "prev field"),
    b(Ctx::SettingsForm, &[Key::right()], Action::FocusRight, "→", "field right"),
    b(Ctx::SettingsForm, &[Key::left()], Action::FocusLeft, "←", "field left"),
    b(Ctx::SettingsForm, &[Key::tab()], Action::FocusNext, "Tab", "next field"),
    b(Ctx::SettingsForm, &[Key::back_tab()], Action::FocusPrev, "S-Tab", "prev field"),
    b(Ctx::SettingsForm, &[Key::ch('i')], Action::EditField, "i", "edit / activate field"),
    b(Ctx::SettingsForm, &[Key::enter()], Action::EditField, "Enter", "edit / activate field"),
    b(Ctx::SettingsForm, &[Key::ch(' ')], Action::EditField, "Space", "edit / activate field"),
    b(Ctx::SettingsForm, &[Key::ch('o')], Action::EditField, "o", "edit / activate field"),
    b(Ctx::SettingsForm, &[Key::ch('W')], Action::SaveSettings, "W", "save changes"),
    b(Ctx::SettingsForm, &[Key::esc()], Action::CloseSettings, "Esc", "back to list"),
    // Search
    b(
        Ctx::Search,
        &[Key::enter()],
        Action::CommitSearch,
        "Enter",
        "apply search",
    ),
    b(
        Ctx::Search,
        &[Key::esc()],
        Action::CloseOverlay,
        "Esc",
        "close",
    ),
    // Confirm
    b(
        Ctx::Confirm,
        &[Key::ch('y')],
        Action::ConfirmYes,
        "y",
        "confirm",
    ),
    b(
        Ctx::Confirm,
        &[Key::enter()],
        Action::ConfirmYes,
        "Enter",
        "confirm",
    ),
    b(
        Ctx::Confirm,
        &[Key::ch('n')],
        Action::ConfirmNo,
        "n",
        "cancel",
    ),
    b(
        Ctx::Confirm,
        &[Key::esc()],
        Action::ConfirmNo,
        "Esc",
        "cancel",
    ),
];

/// All built-in bindings, for the help overlay and table building.
pub fn bindings() -> &'static [Binding] {
    BINDINGS
}
